version: "3.7"
services:
  mongo-node-1:
    image: mongo:3.2
    command: mongod --replSet "rs0" --port 27017
    ports:
      - "27017:27017"

  mongo-node-2:
    image: mongo:3.2
    command: mongod --replSet "rs0" --port 27018
    ports:
      - "27018:27018"

  mongo-node-3:
    image: mongo:3.2
    command: mongod --replSet "rs0" --port 27019
    ports:
      - "27019:27019"

  mongo-node-4:
    image: mongo:3.2
    command: mongod --replSet "rs0" --port 27020
    ports:
      - "27020:27020"

  mongo-node-5:
    image: mongo:3.2
    command: mongod --replSet "rs0" --port 27021
    ports:
      - "27021:27021"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-node-1

  mongo-initialize:
    image: mongo:3.2
    command: sh -c "sleep 3 && mongo mongodb://mongo-node-1 /tmp/configure-replica-set.js"
    volumes:
      - ./configure-replica-set.js:/tmp/configure-replica-set.js

